name = "eigenlayer-ai-agent"
main = "worker.js"
compatibility_date = "2024-04-07"

# Build configuration for Pyodide
[build]
command = "npm run build"

# Enable worker logs
[observability.logs]
enabled = true

# Set the maximum memory
[placement]
mode = "smart"

# Run the agent every 2 minutes
# Using a cron schedule - can be adjusted as needed
[triggers]
crons = ["*/2 * * * *"]

[vars]
# Environment variables will be set during deployment

# Production environment configuration
[env.production]
# Production-specific settings
name = "eigenlayer-ai-agent-production"
# Run the agent every 5 minutes in production for stability
triggers = { crons = ["*/5 * * * *"] }
