name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call: {}
  # Secrets inheritance is handled in the caller

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "AGENT_PRIVATE_KEY=${{ secrets.AGENT_PRIVATE_KEY }}" >> .env
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AGENT_PRIVATE_KEY: ${{ secrets.AGENT_PRIVATE_KEY }}

      - name: Run linters
        run: |
          poetry run black --check .
          poetry run isort --check-only .
          poetry run flake8 .

      - name: Run tests
        run: poetry run pytest
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AGENT_PRIVATE_KEY: ${{ secrets.AGENT_PRIVATE_KEY }}