name: Deploy to Cloudflare

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-ci-tests:
    # Call the reusable CI workflow
    uses: ./.github/workflows/ci.yml
    # Pass secrets required by the test job in ci.yml
    secrets: inherit

  build-docker:
    # Depend on the reusable CI tests job
    needs: run-ci-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: eigenlayer-ai-agent:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64
      
      - name: Export Docker image
        run: |
          mkdir -p ./dist
          docker save eigenlayer-ai-agent:${{ github.sha }} | gzip > ./dist/agent-image.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-image
          path: ./dist/agent-image.tar.gz
          retention-days: 1

  deploy-container:
    # Updated dependency: Only depends on build-docker now
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: agent-image
          path: ./dist
      
      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler
      
      - name: Deploy container to Cloudflare Workers for Containers
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          # Load the image
          gunzip -c ./dist/agent-image.tar.gz | docker load
          
          # Deploy to Cloudflare - REMOVED --secret flags
          wrangler workers deploy-container eigenlayer-ai-agent \
            --image eigenlayer-ai-agent:${{ github.sha }}
            # Secrets (API_KEY, AGENT_PRIVATE_KEY) should be set
            # in the Cloudflare Dashboard for this Worker service. 