name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-python-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          # Export requirements
          poetry export -f requirements.txt --output cloudflare/requirements.txt --without-hashes
          # Install wrangler in the cloudflare directory
          cd cloudflare
          npm install wrangler

      - name: Package Python Code for Cloudflare
        run: |
          # Copy config.json to cloudflare directory
          cp config.json cloudflare/config.json
          
          # Create a ZIP archive of the Python code
          zip -r cloudflare/agent.zip agent abis
          
      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd cloudflare
          # Set environment variables needed for the agent
          echo "Setting required environment variables..."
          npx wrangler secret put API_KEY --env production
          npx wrangler secret put AGENT_PRIVATE_KEY --env production
          
          # Deploy the worker
          npx wrangler deploy 